#!/bin/sh -ex

command -v fetch >/dev/null && DL="fetch -o" || DL="wget -O"
command -v sha256 >/dev/null && SHA256="sha256" || SHA256="sha256sum --binary"
PERL=${PERL:-perl}

TARBALL=gogost-5.13.0.tar.zst
[ -r $TARBALL ] || {
    $DL $TARBALL.tmp http://www.gogost.cypherpunks.ru/$TARBALL
    mv $TARBALL.tmp $TARBALL
}
[ "`$SHA256 < $TARBALL | $PERL -lane 'print $F[0]'`" = "ee0deeb665aee4246c21c8c9f814860502468e37216f43d9acee8c309cc4843e" ]
tar xf $TARBALL
mkdir -p src/crypto/go.cypherpunks.ru/gogost
mv ${TARBALL%.tar.zst} src/crypto/go.cypherpunks.ru/gogost/v5
crypto_version=$(sed -n 's#^.*golang.org/x/crypto \(.*\)$#\1#p' < src/go.mod)
cd src/crypto/go.cypherpunks.ru/gogost/v5
rm -r cmd bench
rm gost341194/pbkdf2_test.go
for len in 256 512 ; do
    fn=gost34112012${len}/hash.go
    echo "func init() { crypto.RegisterHash(crypto.GOSTR34112012${len}, New) }" >> $fn
    $PERL -i -npe '/"hash"/ and print "\t\"crypto\"\n"' $fn
done
find . -name "*.go" -exec $PERL -i -npe "s#go.cypherpunks.ru#crypto/go.cypherpunks.ru#" {} \+
$PERL -i -ne "s#^(require golang.org/x/crypto) .*\$#\$1 $crypto_version#" go.mod
rm go.sum
